//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorDeploymentTest.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgramStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorDeploymentTest.Shared.Resources.ProgramStrings", typeof(ProgramStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string DisclaimerHeading {
            get {
                return ResourceManager.GetString("DisclaimerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notices
        ///
        ///This software was designed primarily to encourage users to explore possible ways of reducing greenhouse gas emissions from farms. The estimates of emission are approximate, and may change appreciably as new scientific findings emerge. Agriculture and Agri-Food Canada does not warrant the reliability of this tool for uses other than education or exploratory gaming of possible practices.
        ///
        ///Copyright/Permission to Reproduce
        ///
        ///Material in this software were produced and/or compiled by Agr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be kept informed about future versions, please send your contact information (including email address) to holos@canada.ca.
        /// </summary>
        public static string EmailSubscriptionText {
            get {
                return ResourceManager.GetString("EmailSubscriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English/Anglais.
        /// </summary>
        public static string EnglishLanguageText {
            get {
                return ResourceManager.GetString("EnglishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English/Anglais.
        /// </summary>
        public static string EnumEnglish {
            get {
                return ResourceManager.GetString("EnumEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francais/French.
        /// </summary>
        public static string EnumFrench {
            get {
                return ResourceManager.GetString("EnumFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francais/French.
        /// </summary>
        public static string FrenchLanguageText {
            get {
                return ResourceManager.GetString("FrenchLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos - a tool to estimate and reduce greenhouse gas emissions from farms..
        /// </summary>
        public static string HolosDescriptionText {
            get {
                return ResourceManager.GetString("HolosDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holos 4.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Language.
        /// </summary>
        public static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0.0.348.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string VersionNumberText {
            get {
                return ResourceManager.GetString("VersionNumberText", resourceCulture);
            }
        }
    }
}
