
name: Deploy to GitHub Pages
2
​
3
# Run workflow on every push to the master branch
4
on:
5
  push:
6
    branches: [ master ]
7
    
8
jobs:
9
  deploy-to-github-pages:
10
    # use ubuntu-latest image to run steps on
11
    runs-on: ubuntu-latest
12
    steps:
13
    # uses GitHub's checkout action to checkout code form the master branch
14
    - uses: actions/checkout@v2
15
    # sets up .NET Core SDK 6
16
    - name: Setup .NET Core SDK
17
      uses: actions/setup-dotnet@v1
18
      with:
19
        dotnet-version: 6.0
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
